name: Cypress Tests

# When to run this workflow

# When to run this workflow
on:
  push:
    branches: [ "master" ]    # Runs on push to main branch
  pull_request:
    branches: [ "master" ]    # Runs on PR to main branch
jobs:
  cypress-run:
    runs-on: ubuntu-latest   # GitHub provides Linux VM

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (Cypress runs on Node)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/register.cy.js, cypress/e2e/login.cy.js, cypress/e2e/newaccount.cy.js, cypress/e2e/funds_transfer.cy.js,cypress/e2e/bill_pay.cy.js"
 

      # (Optional) Upload screenshots if tests fail
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

   
